[web_server]
web_server_01 ansible_host=10.10.1.111

[web_server:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/.ssh/terraform-ssh-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'