- name: Configure protected web server
  hosts: web_server
  become: true

  pre_tasks:
    - name: Load OAuth secrets from SSM Parameter Store
      set_fact:
        oauth2_proxy_client_secret: >-
          {{
            lookup(
              'amazon.aws.ssm_parameter',
              '/task4/oauth2/github-client-secret',
              region='eu-central-1'
            )
          }}

        oauth2_proxy_cookie_secret: >-
          {{
            lookup(
              'amazon.aws.ssm_parameter',
              '/task4/oauth2/cookie-secret',
              region='eu-central-1'
            )
          }}
      no_log: true

  roles:
    - oauth2_proxy
    - nginx