- name: Install packages required by oauth2-proxy
  apt:
    name:
      - ca-certificates
      - tar
      - gzip
    state: present
    update_cache: true

- name: Create oauth2-proxy group
  group:
    name: oauth2-proxy
    system: true
    state: present

- name: Create oauth2-proxy user
  user:
    name: oauth2-proxy
    group: oauth2-proxy
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    state: present

- name: Download oauth2-proxy
  get_url:
    url: >-
      https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v{{ oauth2_proxy_version }}/oauth2-proxy-v{{ oauth2_proxy_version }}.linux-amd64.tar.gz
    dest: /tmp/oauth2-proxy.tar.gz
    mode: "0644"

- name: Extract oauth2-proxy
  unarchive:
    src: /tmp/oauth2-proxy.tar.gz
    dest: /tmp
    remote_src: true
    creates: >-
      /tmp/oauth2-proxy-v{{ oauth2_proxy_version }}.linux-amd64/oauth2-proxy

- name: Install oauth2-proxy binary
  copy:
    src: >-
      /tmp/oauth2-proxy-v{{ oauth2_proxy_version }}.linux-amd64/oauth2-proxy
    dest: /usr/local/bin/oauth2-proxy
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  notify:
    - Restart oauth2-proxy
    - Restart oauth2-proxy-github

- name: Create oauth2-proxy configuration directory
  file:
    path: /etc/oauth2-proxy
    state: directory
    owner: root
    group: oauth2-proxy
    mode: "0750"

- name: Create oauth2-proxy configuration
  template:
    src: oauth2-proxy.cfg.j2
    dest: /etc/oauth2-proxy/oauth2-proxy.cfg
    owner: root
    group: oauth2-proxy
    mode: "0640"
  no_log: true
  notify: Restart oauth2-proxy

- name: Install oauth2-proxy systemd service
  copy:
    src: oauth2-proxy.service
    dest: /etc/systemd/system/oauth2-proxy.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart oauth2-proxy

- name: Enable and start oauth2-proxy
  service:
    name: oauth2-proxy
    state: started
    enabled: true
    daemon_reload: true

#

- name: Create direct GitHub OAuth2 Proxy configuration
  template:
    src: github.cfg.j2
    dest: /etc/oauth2-proxy/github.cfg
    owner: root
    group: oauth2-proxy
    mode: "0640"
  no_log: true
  notify: Restart oauth2-proxy-github

- name: Install direct GitHub OAuth2 Proxy systemd service
  copy:
    src: oauth2-proxy-github.service
    dest: /etc/systemd/system/oauth2-proxy-github.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart oauth2-proxy-github

- name: Validate direct GitHub OAuth2 Proxy configuration
  command:
    cmd: >-
      /usr/local/bin/oauth2-proxy
      --config=/etc/oauth2-proxy/github.cfg
      --config-test
  changed_when: false
  no_log: true

- name: Enable and start direct GitHub OAuth2 Proxy
  service:
    name: oauth2-proxy-github
    state: started
    enabled: true
    daemon_reload: true